### ISSUE TITLE
Where are logs saved locally?

### ISSUE THREAD

**Issue by jnichel** [bloerwald/PetBattleLogKeeper#1]
Hi, I'm trying to find where the logs are saved to the local hard drive, but haven't had any luck.  I'm hoping someone can tell me where they are.  Thank you.

**Comment by bloerwald** [comment]
The data is stored in your account specific saved variables. It should be in `…/World of Warcraft/_retail_/WTF/Account/<your account id>/SavedVariables/PetBattleLogKeeper.lua`.

**Comment by jnichel** [comment]
Thank you very much.  This is exactly what I was looking for.
